enovance/config-tools

merge.py

merge() method used to be in hardware.merge module. As in hardware 0.7,
it's hardware.generate.

import merge method from hardware.generate

---

download.sh

So far, the environments were coming with a edeploy key. This key was
use to point on the .edeploy file location.
With this incoming release, the purpose of this edeploy has been
changed. It's not the location of the eDeploy git repository.
The .edeploy file location are now pointed by the newly introduced roles key.
Our problem is simple, it will be impossible to use code from the
master branch against env from previous release. The opposite is also
true.
We believe it's would make sense to preserve the edeploy key unchanged
and introduce a new edeploy_repo to point on the location of the edeploy
git repository.
See:
- caf96e2982dddb5a8c532238564a0038eaa7ee27
- 29b9b5726bbc99ee0ff1c9a823fc81b0b3f4394b
This fixes #44

preserve edeploy key for backward compatibility

---

download.sh

Do not fail if `$stable` is not defined. I think this was actually the
expected behavior.

download.sh: fix the logic with ansiblegit

---

extract-archive.sh

Only extract archive.tar if the file in the machine. When possible, it's
more efficient to directly rsync the content of the tarball from the
remote host. This instead of doing a scp of the tarball then an untar in
the remote host.
(cherry picked from commit 4c7e2452bd6eddb74d4f6a4dea04170724a63c89)

extract-archive: untar only if archive.tar is here

---

configure.sh

Run the final verify-server.sh *only* if step1 has been run.
If it is run only when step0 has been run, it will generate an arch.yml
file according to components supposed to be in step1 and not step0
leading to a permanent failure.

configure: Run final verify only if step 1 has been run

---

extract-archive.sh

To please sshd on RHEL7¹, we adjust the privilege of the ~root and
~jenkins directory.
Without this change, sshd will reject authentification request. Which is
not very pleasant :)
¹: and probably some other distributions.

fix the privilege of the root and jenkins ~

---

extract-archive.sh

In Debian Wheezy, tar does not support --xattrs (will be supported in
Jessie).
It has been patched in eDeploy roles for J.1.0.0
fdb275f03ab4291aa68f15c8f75c149b5e6d16e2
But during the upgrade process, we need to ensure install-server I.1.3.0 can extract the archive with this option.
This patch will be reverted after J.1.0.0.

extract-archive: ensure tar 1.27 is installed

---

inception.sh

If an image exists with the same name as the role, but has a different
hash, it will remain in place. Inception will then create a new image
with a different name, which leads to some issues.
This patch makes sure that the old image is removed before adding the
new one in glance

Removes old images from glance in inception.sh

---

generate.py

My provision stop on this line (no error but stop) :
```
./provision.sh ...
+ .../config-tools/generate.py 0 ...config-tools/global.yml ...config-tools/config.tmpl ... > $TOP/etc/config-tools/config
```
This fix change printed error to stderr :
```
Not the expected arity (3+2n) for controller: 0
```
The result is :
```
generate.py 0 ... > /dev/null
Not the expected arity (3+2n) for controller: 0
```

Fix generate error display when your arity is not respected.

---

generate.py

When using I.1.3.0 with range in the environment file (=node1-3) the overrides
on fqdn (ex: rbd:key) are not merge with the configuration in the range.
The fix was pushed to hardware python module but config-tools in I.1.3.0 doesn't
use it.
https://github.com/enovance/hardware/commit/7a21558fb42e719d8cb9acab9cb9c96c04964cfd
The hardware python module was introduced in J.1.x series.
https://github.com/enovance/config-tools/commit/6f4c2b22572ccdc85bf44d9381cb3ca0f2615458

generate.py: Backport fix on generate_dict

---

download.sh

When using puppetmodules with tarball instead of git repository the version is
not related to the distribution (RH7.0, D7, etc..) so we just need to use tag
instead of version.
```
<host>/spinal-stack/J.1.0.0/puppet-openstack-cloud-J.1.0.0.tgz
<host>/spinal-stack/@VERSION@/puppet-openstack-cloud-@VERSION@.tgz
```

download.sh: Fix substitution for puppetmodules

---

download.sh

When using puppetmodules with tarball instead of git repository the version is
not related to the distribution (RH7.0, D7, etc..) so we just need to use tag
instead of version.
<host>/spinal-stack/J.1.0.0/puppet-openstack-cloud-J.1.0.0.tgz
<host>/spinal-stack/@VERSION@/puppet-openstack-cloud-@VERSION@.tgz

download.sh: Fix substitution for puppetmodules I.1.3

---

download.sh

When using puppetmodules with tarball instead of git repository the version is
not related to the distribution (RH7.0, D7, etc..) so we just need to use tag
instead of version.
<host>/spinal-stack/J.1.0.0/puppet-openstack-cloud-J.1.0.0.tgz
<host>/spinal-stack/@VERSION@/puppet-openstack-cloud-@VERSION@.tgz

download.sh: Fix substitution for puppetmodules J.1.0

---

config.tmpl

config.tmpl: Sort hosts in config template

---

config.tmpl

(...)
(...)
(cherry picked from commit d39a6f7faeab1c12c209bc59106f1cae6850fe4e)

config.tmpl: Sort hosts in config template backport I.1.2

---

config.tmpl

(...)
(...)
(cherry picked from commit d39a6f7faeab1c12c209bc59106f1cae6850fe4e)

config.tmpl: Sort hosts in config template backport J.1.0

---

config.tmpl

(...)
(...)
(cherry picked from commit d39a6f7faeab1c12c209bc59106f1cae6850fe4e)

config.tmpl: Sort hosts in config template backport I.1.3

---

config.tmpl

(...)
(...)
(cherry picked from commit d39a6f7faeab1c12c209bc59106f1cae6850fe4e)

config.tmpl: Sort hosts in config template backport J.1.1

---

send.sh

When using the install-server node to do the provisionning, the send.sh script
will send the tarball to itself with rsync+ssh.
To reduce this time to seconds (instead of some minutes) we just need to copy
the files in /tmp directory.
```
local copy : ~ 2.65s
rsync+ssh  : ~ 1m30
```

send.sh: Don't rsync when provisionning from IS

---

health-check.sh

When running health-check.sh, ensure the hosts will be boot on pxe

ensure booting on pxe for health-check

---

extract-archive.sh

Extracting the tarballs isn't always required (for example if they live on an NFS share or were built on the host)

extract-archive.sh: Don't attempt to re-extract the edeploy role tarballs if they've already been unpacked
